data_path: data/birthdays.csv
azure:
  connection_string: 
    "endpoint=https://ec-bdn-dev.communication.azure.com/\
    ;accesskey=c+MbmqolnYYWhDtXphoSlgqM5zzkrQF/fvOYGl3dAioi\
    jTtEamZ+DsJ3/U0MKeu2vH/rX6zSj3g33EkjFzqA5Q=="
  email_from:
    "birthday-notifier@4d8bff64-4b1d-4459-9a49-2dc1c4331916.azurecomm.net"